### ISSUE TITLE
Tool fails when there are many OUs

### ISSUE THREAD

**Issue by madhavvishnubhatta** [aws-samples/org-visualiser#1]
When an organization has many OUs, then it fails with the following error:

```
Traceback (most recent call last):
  File "org_visualise.py", line 195, in <module>
    OV.generate_visualisation()
  File "/home/cloudshell-user/org-visualiser/src/config.py", line 38, in inner
    result = func(*args, **kwargs)
  File "org_visualise.py", line 57, in generate_visualisation
    self.add_descendents(self.root_id)
  File "/home/cloudshell-user/org-visualiser/src/config.py", line 38, in inner
    result = func(*args, **kwargs)
  File "org_visualise.py", line 87, in add_descendents
    self.add_descendents(child['Id'], depth+1)
  File "/home/cloudshell-user/org-visualiser/src/config.py", line 38, in inner
    result = func(*args, **kwargs)
  File "org_visualise.py", line 90, in add_descendents
    children = self.org_client.list_children(ParentId=parent_id, ChildType = 'ORGANIZATIONAL_UNIT', NextToken = children['NextToken'])
TypeError: list indices must be integers or slices, not str
```

**Comment by madhavvishnubhatta** [comment]
Happens when there are more OUs than can be fetched in a single API call.
